

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Contact
{

    public int ContactKey { get; set; }

    public string ContactNumber { get; set; }

    public Nullable<int> ContactTypeKey { get; set; }

    public Nullable<int> PersonKey { get; set; }



    public virtual ContactType ContactType { get; set; }

    public virtual Person Person { get; set; }

}


public partial class ContactType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContactType()
    {

        this.Contacts = new HashSet<Contact>();

    }


    public int ContactTypeKey { get; set; }

    public string ContactTypeName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contact> Contacts { get; set; }

}


public partial class Employee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {

        this.Positions = new HashSet<Position>();

    }


    public int EmployeeKey { get; set; }

    public Nullable<int> PersonKey { get; set; }

    public System.DateTime EmployeeHireDate { get; set; }

    public Nullable<decimal> EmployeeAnnualSalary { get; set; }



    public virtual Person Person { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Position> Positions { get; set; }

}


public partial class Person
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Person()
    {

        this.Contacts = new HashSet<Contact>();

        this.Employees = new HashSet<Employee>();

        this.PersonAddresses = new HashSet<PersonAddress>();

    }


    public int PersonKey { get; set; }

    public string PersonLastName { get; set; }

    public string PersonFirstName { get; set; }

    public string PersonEmail { get; set; }

    public byte[] PersonPassWord { get; set; }

    public System.DateTime PersonEntryDate { get; set; }

    public Nullable<int> PersonPassWordSeed { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contact> Contacts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PersonAddress> PersonAddresses { get; set; }

}


public partial class PersonAddress
{

    public int PersonAddressKey { get; set; }

    public string PersonAddressApt { get; set; }

    public string PersonAddressStreet { get; set; }

    public string PersonAddressCity { get; set; }

    public string PersonAddressState { get; set; }

    public string PersonAddressZip { get; set; }

    public Nullable<int> PersonKey { get; set; }



    public virtual Person Person { get; set; }

}


public partial class Position
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Position()
    {

        this.Employees = new HashSet<Employee>();

    }


    public int PositionKey { get; set; }

    public string PositionName { get; set; }

    public string PositionDescription { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Employee> Employees { get; set; }

}

